name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-2'

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://today-law --delete

    - name: Invalidate cache CloudFront
      uses: chetan/invalidate-cloudfront-action@master
      env:
        # CloudFront id 세팅
        DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
        PATHS: '/templates/index.html'
      continue-on-error: true

#name: frontend

# main 브랜치로 push될 때 스크립트를 실행
#on:
#  push:
#    branches:
#      - main
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    env:
#      # IAM key 세팅 [ repo - settings - secrets - new repository secret ]
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_REGION: 'ap-northeast-2'
#
#    steps:
#      - name: Checkout source code.
#        uses: actions/checkout@master
#
#      - name: Upload binary to S3 bucket
#        uses: jakejarvis/s3-sync-action@master # 이미 정의된 action을 가져와서 사용
#        with:
#          args: --acl public-read --exclude '*' --include '.templates/index.html'
#        env:
#           # s3 bucket 이름 세팅 [ repo - settings - secrets - new repository secret ]
#          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
#
#      - name: Invalidate cache CloudFront
#        uses: chetan/invalidate-cloudfront-action@master
#        env:
#          # CloudFront id 세팅
#          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
#          PATHS: '/index.html'
#        continue-on-error: true